[GeneralSettings]
# creating cache files on github makes no sense
Packager/CreateCache = False


[Paths]
CCACHE_DIR = ${Env:HOME}/ccache


[Shortcuts]
# Force un timeout réseau rapide (en secondes) si un miroir rame
DownloadConnectTimeout = 30
# Force Craft à utiliser curl au lieu de wget/wget2 pour la récupération des binaires
DownloadPackager = curl

[BlueprintSettings]
# Force la compilation locale de kshimgen pour s'aligner sur la GLIBC du conteneur
dev-utils/kshimgen.useBinary = False

[Compile]
UseCCache = True
# Augmente le timeout des commandes internes à 1 heure (3600 secondes)
Timeout = 3600

[linux-gcc-x86_64]
Environment/SourceCommand = export PKG_CONFIG_PATH=(/usr/bin/pkg-config --variable pc_path pkg-config) && source /opt/rh/gcc-toolset-14/enable

[linux-gcc-x86_64-debug]
Environment/SourceCommand = export PKG_CONFIG_PATH=(/usr/bin/pkg-config --variable pc_path pkg-config) && source /opt/rh/gcc-toolset-14/enable
